--check to see if the tables were populated and updated
SELECT * FROM BLJOHN0313.CUSTOMER;
SELECT * FROM BLJOHN0313.CAR;
SELECT * FROM BLJOHN0313.REPAIRSHOP;
SELECT * FROM BLJOHN0313.Technician;
SELECT * FROM BLJOHN0313.CarRepairHistory;
SELECT * FROM BLJOHN0313.CarRepairInvoice;
SELECT * FROM BLJOHN0313.CARPART;



--Start from the bottom and go up
DELETE FROM BLJOHN0313.CUSTOMER;
DELETE FROM BLJOHN0313.CAR;
DELETE FROM BLJOHN0313.REPAIRSHOP;
DELETE FROM BLJOHN0313.Technician;
DELETE FROM BLJOHN0313.CarRepairHistory;
DELETE FROM BLJOHN0313.CarRepairInvoice;
DELETE FROM BLJOHN0313.CARPART;

--Reset PK values to start at 1
DBCC CHECKIDENT ('bljohn0313.Customer', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.Car', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.RepairShop', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.Technician', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.CarRepairHistory', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.CarRepairInvoice', RESEED, 0)
DBCC CHECKIDENT ('bljohn0313.CarPart', RESEED, 0)

--Drop Tables
DROP TABLE BLJOHN0313.Car;
DROP TABLE BLJOHN0313.Technician;
DROP TABLE BLJOHN0313.Customer;
DROP TABLE BLJOHN0313.CarRepairHistory;
DROP TABLE BLJOHN0313.CarRepairInvoice;
DROP TABLE BLJOHN0313.CarPart;
DROP TABLE BLJOHN0313.RepairShop;
